# Generated by Django 4.2.1 on 2023-11-25 23:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishNoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('known_language_noun', models.CharField(max_length=64)),
                ('article', models.CharField(default='The', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['known_language_noun'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GermanNoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language_noun', models.CharField(max_length=64)),
                ('last_test', models.DateField(auto_now=True)),
                ('number_of_tests', models.PositiveIntegerField(default=0)),
                ('correct_tests', models.PositiveIntegerField(default=0)),
                ('percentage_correct', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('article', models.CharField(choices=[('Der', 'Der'), ('Die', 'Die'), ('Das', 'Das')], max_length=3)),
                ('translations', models.ManyToManyField(to='language.englishnoun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_language_noun'],
                'abstract': False,
            },
        ),
    ]
